sudo: required

language: cpp

matrix:
  include:
    - compiler: gcc
      python: "2.7"
      dist: trusty
      addons:
        apt:
          packages:
            - python-dev
      env: PYTHONVERSION=python2
    - compiler: gcc
      python: "3.4"
      dist: trusty
      addons:
        apt:
          packages:
            - python3.4-dev
      env: PYTHONVERSION=python3.4
    - compiler: gcc
      python: "3.6.1"
      dist: trusty
      addons:
        apt:
          packages:
            - python3
      env: PYTHONVERSION=python3

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update -y
  - sudo apt-get install python3.6 python3.6-dev -y

script:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - unset PYTHON_CFLAGS
  - ./autogen.sh
  - ./configure
  - make
  - make test
