sudo: required
compiler: gcc
dist: trusty
language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo add apt-repository ppa:jonathonf/python-3.6 -y
  - sudo apt-get update -y
  - sudo apt-get install python3.6 python3.6-dev -y

addons:
  apt:
    packages:
      - autotools-dev
      - g++
      - pkg-config
      - python-dev
      - python3-dev

script:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - unset PYTHON_CFLAGS
  - ./autogen.sh
  - ./configure
  - make
  - ./runtests.sh python
